Repository greedy-team/ddarahang-fe, pull requests merged in 2025-02, with the labels that each got.

#5 feature: HEADER UI 구현
  .storybook/preview.tsx
  public/icon/LoginIcon.svg
  public/image/japan.jpg
  public/image/korea.jpg
  public/image/search.svg
  src/Globalstyle.tsx
  src/components/common/Button/CircleButton/CircleButton.style.tsx
  src/components/common/Button/CircleButton/CircleButton.tsx
  src/components/common/GlobalHeader/GlobalHeader.style.tsx
  src/components/common/GlobalHeader/GlobalHeader.tsx
  src/components/common/Logo/Logo.style.tsx
  src/components/common/Logo/Logo.tsx
  src/components/common/SelectItem/SelectOption.style.tsx
  src/components/common/SelectItem/SelectOption.tsx
  src/components/common/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/SelectOptionList/SelectOptionList.tsx
  src/components/common/SelectTab/SelectTab.style.tsx
  src/components/common/SelectTab/SelectTab.tsx
  src/components/common/SelectTrigger/SelectTrigger.tsx
  src/components/common/SelectTrigger/selectTrigger.style.tsx
  src/components/main/Header/Header.style.tsx
  src/components/main/Header/Header.tsx
  src/components/main/Select/Select.style.tsx
  src/components/main/Select/Select.tsx
  src/constants/index.ts
  src/stories/Button/CircleButton.stories.tsx
  src/stories/Header/Header.stories.tsx
  src/stories/Logo/Logo.stories.tsx
  src/stories/Select/Select.stories.tsx
  src/stories/Select/SelectOption.stories.tsx
  src/stories/Select/SelectOptionList.stories.tsx
  src/stories/Select/SelectTrigger.stories.tsx
  src/type/index.ts
Labels: feature

#6 feature: 메인페이지 카드 컴포넌트 제작
  src/components/main/YoutubeCard/YoutubeCard.style.tsx
  src/components/main/YoutubeCard/YoutubeCard.tsx
  src/stories/Card/YoutubeCard.stories.tsx
Labels: feature

#9 fix: 공통 사이즈 수정
  src/App.tsx
  src/components/common/Button/CircleButton/CircleButton.style.tsx
  src/components/common/GlobalHeader/GlobalHeader.style.tsx
  src/components/common/Logo/Logo.style.tsx
  src/components/common/SelectItem/SelectOption.style.tsx
  src/components/common/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/SelectTab/SelectTab.style.tsx
  src/components/common/SelectTrigger/selectTrigger.style.tsx
  src/styles/Theme.ts
Labels: style

#11 feature: Footer UI 구현
  src/components/main/Footer/Footer.style.tsx
  src/components/main/Footer/Footer.tsx
  src/stories/Footer/Footer.stories.tsx
Labels: feature, style

#13 refactor: 필요 없는 파일 삭제
  src/components/common/Button/Button.tsx
  src/constants/Countries.ts
  src/stories/Button.stories.tsx
  src/type/index.ts
Labels: refactor

#17 feature: 메인터넌스 UI 제작
  src/Globalstyle.tsx
  src/components/common/Button/RectangleButton/RectangleButton.style.tsx
  src/components/common/Button/RectangleButton/RectangleButton.tsx
  src/pages/Maintenance/MaintenancePage.style.tsx
  src/pages/Maintenance/MaintenancePage.tsx
  src/stories/Button/RectangleButton.stories.tsx
  src/stories/Page/MaintenancePage.stories.tsx
Labels: feature

#19 feature: 드롭다운 UI 구현
  public/icon/DownArrow.svg
  src/components/common/Dropdown/Dropdown/Dropdown.style.tsx
  src/components/common/Dropdown/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/DropdownItem/DropdownItem.style.tsx
  src/components/common/Dropdown/DropdownItem/DropdownItem.tsx
  src/components/common/Dropdown/DropdownList/DropdownList.style.tsx
  src/components/common/Dropdown/DropdownList/DropdownList.tsx
  src/components/common/Dropdown/DropdownTrigger/DropdownTrigger.style.tsx
  src/components/common/Dropdown/DropdownTrigger/DropdownTrigger.tsx
  src/components/main/SortDropdown/SortDropdown.tsx
  src/stories/Dropdown/Dropdown.stories.tsx
  src/styles/Theme.ts
Labels: feature, style

#22 style: 셀렉 박스 UI 완성
  public/image/region/busan.jpg
  public/image/region/chungcheongbuk-do.jpg
  public/image/region/chungcheongnam-do.jpg
  public/image/region/daegu.jpg
  public/image/region/daejeon.jpg
  public/image/region/fukuoka.jpg
  public/image/region/gangwon-do.jpg
  public/image/region/gwangju.jpg
  public/image/region/gyeonggi-do.jpg
  public/image/region/gyeongsangbuk-do.jpg
  public/image/region/gyeongsangnam-do.jpg
  public/image/region/incheon.jpg
  public/image/region/jeju-do.jpg
  public/image/region/jeolabuk-do.jpg
  public/image/region/jeolanam-do.jpg
  public/image/region/osaka.jpg
  public/image/region/tokyo.jpg
  public/image/region/ulsan.jpg
  src/Globalstyle.tsx
  src/components/common/SelectItem/SelectOption.style.tsx
  src/components/common/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/SelectOptionList/SelectOptionList.tsx
  src/components/common/SelectTab/SelectTab.tsx
  src/components/common/SelectTrigger/SelectTrigger.tsx
  src/components/common/SelectTrigger/selectTrigger.style.tsx
  src/components/main/Header/Header.style.tsx
  src/components/main/Select/Select.style.tsx
  src/components/main/Select/Select.tsx
  src/constants/index.ts
Labels: refactor, style

#25 feature: travel course card UI 구현
  src/components/common/PlaceCard/PlaceCardItem/PlaceCardItem.style.tsx
  src/components/common/PlaceCard/PlaceCardItem/PlaceCardItem.tsx
  src/components/common/PlaceCard/PlaceCardList/PlaceCardList.style.tsx
  src/components/common/PlaceCard/PlaceCardList/PlaceCardList.tsx
  src/stories/Card/PlaceCard.stories.tsx
  src/stories/Card/PlaceCardList.stories.tsx
  src/styles/Theme.ts
Labels: feature, style

#31 feature : 라우팅 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/pages/MainPage.tsx
  src/router/index.tsx
Labels: feature

#32 feature: 메인 페이지 페이지 네이션 기능 구현
  src/Globalstyle.tsx
  src/apis/getTravelVideoList.ts
  src/components/common/Button/PageButton/PageButton.style.tsx
  src/components/common/Dropdown/Dropdown/Dropdown.style.tsx
  src/components/common/GlobalHeader/GlobalHeader.style.tsx
  src/components/common/Logo/Logo.style.tsx
  src/components/common/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/SelectTab/SelectTab.style.tsx
  src/components/common/SelectTab/SelectTab.tsx
  src/components/common/SelectTrigger/selectTrigger.style.tsx
  src/components/main/Header/Header.style.tsx
  src/components/main/Header/Header.tsx
  src/components/main/Pagination/Pagination.style.tsx
  src/components/main/Pagination/Pagination.tsx
  src/components/main/Select/Select.style.tsx
  src/components/main/Select/Select.tsx
  src/components/main/SortDropdown/SortDropdown.style.tsx
  src/components/main/SortDropdown/SortDropdown.tsx
  src/components/main/TravelVideoList/TravelVideoList.style.tsx
  src/components/main/TravelVideoList/TravelVideoList.tsx
  src/components/main/YoutubeCard/YoutubeCard.style.tsx
  src/components/main/YoutubeCard/YoutubeCard.tsx
  src/constants/index.ts
  src/hooks/quries/useGetTravelVideoList.tsx
  src/mocks/data/travelListMockData.ts
  src/pages/Main/MainPage.style.tsx
  src/pages/Main/MainPage.tsx
  src/pages/MainPage.tsx
  src/router/index.tsx
Labels: feature, style

#37 feature: 셀렉 박스 기능 구현
  src/App.tsx
  src/components/common/Button/CircleButton/CircleButton.style.tsx
  src/components/common/SelectItem/SelectOption.tsx
  src/components/common/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/SelectOptionList/SelectOptionList.tsx
  src/components/common/SelectTab/SelectTab.style.tsx
  src/components/common/SelectTab/SelectTab.tsx
  src/components/common/SelectTrigger/SelectTrigger.tsx
  src/components/common/SelectTrigger/selectTrigger.style.tsx
  src/components/main/Header/Header.tsx
  src/components/main/Main.tsx
  src/components/main/Select/Select.style.tsx
  src/components/main/Select/Select.tsx
  src/constants/index.ts
  src/hooks/quries/useGetTravelVideoList.tsx
  src/hooks/select/useDetectClose.tsx
  src/hooks/select/useSelectOptionContext.tsx
  src/pages/Main/MainPage.tsx
  src/store/SelectOptionContext.tsx
  src/stories/Select/SelectTrigger.stories.tsx
  src/types/index.ts
  src/utils/index.ts
Labels: feature

#42 feature: 상세 페이지 탭 기능 구현
  src/App.tsx
  src/components/common/Button/RectangleButton/RectangleButton.tsx
  src/components/common/PlaceCard/PlaceCardItem.style.tsx
  src/components/common/PlaceCard/PlaceCardItem.tsx
  src/components/common/Tabs/Tab/Tab.style.tsx
  src/components/common/Tabs/Tab/Tab.tsx
  src/components/common/Tabs/TabPanel/TabPanel.tsx
  src/components/common/TravelMap/TravelMap.tsx
  src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
  src/components/common/TravelMapMarker/TravelMapMarker.tsx
  src/components/detail/TravelCourse/TravelCourse.style.tsx
  src/components/detail/TravelCourse/TravelCourse.tsx
  src/hooks/select/useSelectedPanel.tsx
  src/mocks/data/travelCourseDetailMockData.ts
  src/pages/TravelCourse/TravelCoursePage.style.tsx
  src/pages/TravelCourse/TravelCoursePage.tsx
  src/store/SelectedPanelContext.tsx
  src/stories/Button/RectangleButton.stories.tsx
  src/types/index.ts
Labels: feature
