Repository greedy-team/ddarahang-fe, pull requests merged in 2025-03, with the labels that each got.

#50 Fix: build error 제거
  .storybook/preview.tsx
  src/components/detail/TravelCourse/TravelCourse.tsx
  src/hooks/quries/useGetTravelVideoList.tsx
  src/pages/Maintenance/MaintenancePage.tsx
  src/stories/Button/PageButton.stories.tsx
  src/stories/Card/PlaceCard.stories.tsx
  src/stories/Card/YoutubeCard.stories.tsx
  src/stories/Dropdown/Dropdown.stories.tsx
  src/stories/Header/Header.stories.tsx
  src/stories/Pagination/Pagination.stories.tsx
  src/stories/Select/Select.stories.tsx
  src/stories/Select/SelectOption.stories.tsx
  src/stories/Select/SelectOptionList.stories.tsx
  src/stories/Select/SelectTrigger.stories.tsx
  src/stories/Tab/Tab.stories.tsx
  src/stories/TravelCourse/TravelCourse.stories.tsx
  src/stories/Video/VideoSection.stories.tsx
Labels: bug

#49 chore: ci / cd 워크플로 작성 #47
  .github/workflows/deploy.yml
  .storybook/preview.tsx
  src/components/detail/TravelCourse/TravelCourse.tsx
  src/hooks/quries/useGetTravelVideoList.tsx
  src/pages/Maintenance/MaintenancePage.tsx
  src/stories/Button/PageButton.stories.tsx
  src/stories/Card/PlaceCard.stories.tsx
  src/stories/Card/YoutubeCard.stories.tsx
  src/stories/Dropdown/Dropdown.stories.tsx
  src/stories/Header/Header.stories.tsx
  src/stories/Pagination/Pagination.stories.tsx
  src/stories/Select/Select.stories.tsx
  src/stories/Select/SelectOption.stories.tsx
  src/stories/Select/SelectOptionList.stories.tsx
  src/stories/Select/SelectTrigger.stories.tsx
  src/stories/Tab/Tab.stories.tsx
  src/stories/TravelCourse/TravelCourse.stories.tsx
  src/stories/Video/VideoSection.stories.tsx
Labels: chore

#51 refactor: UI 를 개선하였습니다.
  package-lock.json
  package.json
  src/components/common/Button/CircleButton/CircleButton.style.tsx
  src/components/common/Button/CircleButton/CircleButton.tsx
  src/components/common/Button/PageButton/PageButton.style.tsx
  src/components/common/Button/PageButton/PageButton.tsx
  src/components/common/Button/RectangleButton/RectangleButton.tsx
  src/components/common/Dropdown/DropdownList/DropdownList.style.tsx
  src/components/common/Dropdown/DropdownList/DropdownList.tsx
  src/components/common/GlobalHeader/GlobalHeader.style.tsx
  src/components/common/GlobalHeader/GlobalHeader.tsx
  src/components/common/Loading/Loading.style.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/PlaceCard/PlaceCardItem.style.tsx
  src/components/common/PlaceCard/PlaceCardItem.tsx
  src/components/common/Select/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/Select/SelectOptionList/SelectOptionList.tsx
  src/components/common/Select/SelectTab/SelectTab.tsx
  src/components/common/Select/SelectTrigger/SelectTrigger.tsx
  src/components/common/Select/SelectTrigger/selectTrigger.style.tsx
  src/components/common/Tabs/Tab/Tab.style.tsx
  src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
  src/components/detail/TravelCourse/TravelCourse.tsx
  src/components/detail/Video/VideoSection.style.tsx
  src/components/detail/Video/VideoSection.tsx
  src/components/main/Select/Select.style.tsx
  src/components/main/Select/Select.tsx
  src/components/main/TravelVideoList/TravelVideoList.style.tsx
  src/components/main/TravelVideoList/TravelVideoList.tsx
  src/components/main/YoutubeCard/YoutubeCard.style.tsx
  src/components/main/YoutubeCard/YoutubeCard.tsx
  src/constants/index.ts
  src/hooks/quries/useGetTravelVideoList.tsx
  src/hooks/screen/useMediaScreen.tsx
  src/hooks/select/useDetectClose.tsx
  src/pages/Main/MainPage.tsx
  src/pages/TravelCourse/TravelCoursePage.tsx
  src/styles/Theme.ts
Labels: bug, refactor, style

#63 refactor: 나라, 지역 이미지 URL 변경
  public/image/japan.jpg
  public/image/korea.jpg
  public/image/region/busan.jpg
  public/image/region/chungcheongbuk-do.jpg
  public/image/region/chungcheongnam-do.jpg
  public/image/region/daegu.jpg
  public/image/region/daejeon.jpg
  public/image/region/fukuoka.jpg
  public/image/region/gangwon-do.jpg
  public/image/region/gwangju.jpg
  public/image/region/gyeonggi-do.jpg
  public/image/region/gyeongsangbuk-do.jpg
  public/image/region/gyeongsangnam-do.jpg
  public/image/region/incheon.jpg
  public/image/region/jeju-do.jpg
  public/image/region/jeolabuk-do.jpg
  public/image/region/jeolanam-do.jpg
  public/image/region/osaka.jpg
  public/image/region/tokyo.jpg
  public/image/region/ulsan.jpg
  src/constants/index.ts
Labels: refactor

#67 refactor: 페이지네이션 최대 5개로 변경 #58
  public/icon/prev.svg
  src/components/main/Pagination/Pagination.tsx
  src/constants/index.ts
Labels: refactor

#72 feature: 상세 정보 페이지의 맵 설정
  src/Globalstyle.tsx
  src/components/common/TravelMap/TravelMap.tsx
  src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
  src/components/common/TravelMapMarker/TravelMapMarker.tsx
  src/styles/Theme.ts
Labels: feature, refactor, style

#78 test: 통합 테스트 작성
  .eslintrc.json
  package-lock.json
  package.json
  src/components/common/Button/CircleButton/CircleButton.tsx
  src/components/common/Select/SelectOptionList/SelectOptionList.tsx
  src/components/detail/Video/VideoSection.tsx
  src/stories/Dropdown/Dropdown.stories.tsx
  src/stories/Select/SelectOptionList.stories.tsx
  src/stories/Tab/Tab.stories.tsx
  src/tests/Render.tsx
  src/tests/components/main/Header.test.tsx
  src/tests/components/main/Pagination.test.tsx
  src/tests/components/main/SortDropdown.test.tsx
  src/tests/components/main/TravelVideoList.test.tsx
  src/tests/components/travelcourse/GlobalHeader.test.tsx
  src/tests/components/travelcourse/TabPanel.test.tsx
  src/tests/components/travelcourse/TravelCourse.test.tsx
  src/tests/components/travelcourse/VideoSection.test.tsx
  src/tests/data/mockData.tsx
  src/tests/setup.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: feature, perf, test

#82 fix: 드롭다운 닫기 문제 해결
  src/components/main/SortDropdown/SortDropdown.tsx
Labels: bug

#84 perf: 이미지 경로 수정 및 최적화
  src/components/common/Image/LazyImage.tsx
  src/components/common/Select/SelectItem/SelectOption.style.tsx
  src/components/common/Select/SelectItem/SelectOption.tsx
  src/components/main/YoutubeCard/YoutubeCard.style.tsx
  src/constants/index.ts
  src/hooks/image/useLazyLoadImage.ts
  src/types/index.ts
  src/utils/index.ts
Labels: feature, refactor, perf

#90 fix: 페이지네이션 초기화 문제 수정
  src/components/common/Select/SelectItem/SelectOption.tsx
  src/components/common/Select/SelectOptionList/SelectOptionList.tsx
  src/components/main/Header/Header.tsx
  src/components/main/Select/Select.tsx
  src/hooks/select/useSubmitOption.tsx
  src/pages/Main/MainPage.tsx
  src/stories/Header/Header.stories.tsx
  src/stories/Select/Select.stories.tsx
  src/stories/Select/SelectOption.stories.tsx
  src/stories/Select/SelectOptionList.stories.tsx
  src/tests/components/main/Header.test.tsx
Labels: bug

#92 Feature: GA 및 SEO 최적화
  index.html
  public/robots.txt
Labels: feature, perf

#94 feature: 메인페이지 반응형 디자인 #93
  src/Globalstyle.tsx
  src/components/common/GlobalHeader/GlobalHeader.style.tsx
  src/components/common/Select/SelectOptionList/SelectOptionList.style.tsx
  src/components/common/Select/SelectOptionList/SelectOptionList.tsx
  src/components/common/Select/SelectTab/SelectTab.style.tsx
  src/components/common/Select/SelectTab/SelectTab.tsx
  src/components/common/Select/SelectTrigger/SelectTrigger.tsx
  src/components/common/Select/SelectTrigger/selectTrigger.style.tsx
  src/components/main/Header/Header.style.tsx
  src/components/main/Select/Select.style.tsx
  src/components/main/TravelVideoList/TravelVideoList.style.tsx
Labels: style

#96 Chore/95 cicd pipe
  .github/workflows/deploy.yml
Labels: chore

#107 feature: 상세페이지 반응형 디자인 추가
  public/icon/map.svg
  src/components/common/Button/CircleButton/CircleButton.style.tsx
  src/components/common/Button/CircleButton/CircleButton.tsx
  src/components/common/GlobalHeader/GlobalHeader.style.tsx
  src/components/common/GlobalHeader/GlobalHeader.tsx
  src/components/common/Logo/Logo.tsx
  src/components/detail/TravelCourse/TravelCourse.style.tsx
  src/components/detail/Video/VideoSection.style.tsx
  src/components/detail/Video/VideoSection.tsx
  src/components/main/Header/Header.tsx
  src/pages/TravelCourse/TravelCoursePage.style.tsx
  src/pages/TravelCourse/TravelCoursePage.tsx
  src/stories/Video/VideoSection.stories.tsx
  src/tests/components/main/Header.test.tsx
  src/tests/components/main/TravelVideoList.test.tsx
  src/tests/components/travelcourse/GlobalHeader.test.tsx
  src/tests/components/travelcourse/TravelCourse.test.tsx
  src/tests/components/travelcourse/VideoSection.test.tsx
Labels: feature

#106 docs: update-read.me
  README.md
Labels: docs

#112 refactor: 리뷰 반영
  src/components/common/GlobalHeader/GlobalHeader.tsx
  src/components/common/TravelMap/TravelMap.tsx
  src/components/main/Header/Header.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Maintenance/MaintenancePage.tsx
  src/pages/NotFound/NotFoundPage.tsx
  src/pages/TravelCourse/TravelCoursePage.tsx
  src/stories/Header/Header.stories.tsx
  src/stories/Logo/Logo.stories.tsx
  src/tests/components/main/Header.test.tsx
  src/tests/components/travelcourse/GlobalHeader.test.tsx
Labels: refactor

#115 refactor:style travel course responsive
  src/components/common/Tabs/TabPanel/TabPanel.style.tsx
  src/components/detail/TravelCourse/TravelCourse.style.tsx
  src/pages/TravelCourse/TravelCoursePage.style.tsx
Labels: refactor, style

#118 feature: 베트남, 중국 데이터 추가 #117
  src/components/common/Select/SelectOptionList/SelectOptionList.tsx
  src/constants/index.ts
  src/types/index.ts
  src/utils/index.ts
Labels: feature

#119 style: 마커 색 및 크기 변경
  src/components/common/TravelMapMarker/TravelMapMarker.style.tsx
  src/styles/Theme.ts
Labels: style

#121 refactor: 상세 페이지 모바일 디자인 변경
  src/components/detail/TravelCourse/TravelCourse.style.tsx
  src/components/detail/Video/VideoSection.style.tsx
  src/components/detail/Video/VideoSection.tsx
  src/pages/TravelCourse/TravelCoursePage.style.tsx
  src/pages/TravelCourse/TravelCoursePage.tsx
Labels: refactor
